build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: true
    threshold: 20

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 4
  MaxLineLength:
    active: true
    maxLineLength: 140
  WildcardImport:
    active: false
  UnusedParameter:
    active: true
  UnusedPrivateMember:
    active: true
  NewLineAtEndOfFile:
    active: true

naming:
  FunctionNaming:
    active: true
    # Allow PascalCase for @Composable functions.
    functionPattern: '([a-z][a-zA-Z0-9]*)|([A-Z][a-zA-Z0-9]*)'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9]*'

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - CancellationException

potential-bugs:
  UnsafeCallOnNullableType:
    active: true
  LateinitUsage:
    active: false
